name: "get-templates"
version: 0.0.3
usage: "helm get-templates RELEASENAME [--revision n] [--namespace NAMESPACENAME]"
description: |-
  "Get templates for helm release e.g. helm get-templates RELEASENAME [--revision N] [--namespace NAMESPACES]"
platformCommand:
  - os: linux
    arch: amd64
    command: "$HELM_PLUGIN_DIR/get-templates"
  - os: windows
    arch: amd64
    command: "$HELM_PLUGIN_DIR\\get-templates.exe"
