# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI and release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run pkg
    - name: Create windows archive
      run: cd helm-get-templates-windows-amd64 && /bin/tar -cvzf ../helm-get-templates-windows-amd64.tar.gz *
    - name: Create linux archive
      run: cd helm-get-templates-linux-amd64 && /bin/tar -cvzf ../helm-get-templates-linux-amd64.tar.gz *
    - name: Upload windows archives
      uses: actions/upload-artifact@v3
      with:
        name: helm-get-templates-windows-amd64.tar.gz
        path: helm-get-templates-windows-amd64.tar.gz
    - name: Upload linux archives
      uses: actions/upload-artifact@v3
      with:
        name: helm-get-templates-linux-amd64.tar.gz
        path: helm-get-templates-linux-amd64.tar.gz
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: helm-get-templates-windows-amd64.tar.gz
      - uses: actions/download-artifact@v3
        with:
          name: helm-get-templates-linux-amd64.tar.gz
      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            helm-get-templates-windows-amd64.tar.gz
            helm-get-templates-linux-amd64.tar.gz


